export const IS_SUBSCRIBED = 'IS_SUBSCRIBED';

export const PRESCORING_OFFERS = 'PRESCORING_OFFERS';
export const IS_OFFER_ACCEPTED = 'IS_OFFER_ACCEPTED';
export const SCORING = 'SCORING';
export const STEP = 'STEP';
export const IS_PAYMENT_SCHEDULE_ACCEPTED = 'IS_PAYMENT_SCHEDULE_ACCEPTED';
export const IS_SIGN_DOCUMENT = 'IS_SIGN_DOCUMENT';
